"use client";

import { useEffect, useState } from "react";
import { ShieldAlert, CheckCircle2 } from "lucide-react";

export default function DisclaimerModal() {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    // Check if the user has already acknowledged the disclaimer
    const hasAccepted = localStorage.getItem("dermarare_disclaimer_accepted");
    if (!hasAccepted) {
      setIsOpen(true);
    }
  }, []);

  const handleAccept = () => {
    localStorage.setItem("dermarare_disclaimer_accepted", "true");
    setIsOpen(false);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/80 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-2xl border border-slate-200 animate-fade-in">
        <div className="flex items-center space-x-3 text-amber-500 mb-4">
          <ShieldAlert className="h-8 w-8 animate-pulse" />
          <h2 className="text-xl font-bold text-slate-800">Important Medical Disclaimer</h2>
        </div>
        
        <div className="space-y-3.5 text-sm text-slate-600 leading-relaxed">
          <p className="font-semibold text-slate-800">
            Please read and acknowledge the following statement before using the DermaRare AI platform:
          </p>
          <div className="bg-slate-50 border-l-4 border-amber-500 p-4 rounded-r-lg space-y-2">
            <p className="font-medium text-amber-800">EDUCATIONAL USE ONLY</p>
            <p className="text-slate-700 text-xs">
              DermaRare AI is an educational resource designed to raise awareness about 30 rare skin diseases. The AI symptom checker and chatbot represent probability-based matching algorithms and do not provide medical diagnosis.
            </p>
          </div>
          <p>
            The content, symptom matching results, and chat interactions generated by this site are not a substitute for professional medical advice, diagnosis, or treatment.
          </p>
          <p className="text-xs text-slate-500">
            By clicking "I Understand & Agree", you confirm that you will consult a qualified dermatologist or medical practitioner for any clinical evaluations or diagnostic concerns.
          </p>
        </div>

        <div className="mt-6 flex justify-end">
          <button
            onClick={handleAccept}
            className="w-full sm:w-auto flex items-center justify-center space-x-2 bg-gradient-to-r from-blue-600 to-cyan-500 text-white font-semibold px-6 py-3 rounded-xl shadow-md hover:from-blue-700 hover:to-cyan-600 hover:-translate-y-0.5 transition-all duration-150 cursor-pointer"
          >
            <CheckCircle2 className="h-5 w-5" />
            <span>I Understand & Agree</span>
          </button>
        </div>
      </div>
    </div>
  );
}
